### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Zaexides** [Zaexides/SteamWorld#12]
# Issue Report
*Please remove any unnecessary or unused fields. You don't have to, but it's appreciated :)*

* **What's the type of issue?**
  * *Bug report*

### Bug Report
  * **What's the mod version?**
    * *SteamWorld 1.12.2-0.3.0.3*

  * **What's the forge version?**
    * *Forge 14.23.2.2611*

  * **What were you doing when the bug occurred?**
    * *N/A*

  * **What happened that should not have happened?**
    * *NullRefEx from minecraft NBT system when writing to fluid NBT in the SteamGenerator*
  
  * **Please post your crashlog and forge logs here.**
    * *https://pastebin.com/4vw3VMgA*
    
  * **Do you have any additional information? Any info helps!**
    * *N/A*

**Comment by navaroneee** [comment]
Hi Zaexides, sorry post in wrong place at first time.
I'm trying put water, coal and the output is to Magneticraft Small Steam engine, using Endeio' s fluid conduit
I try reproduce the issue again but nothing happens.
The issue close server, but nothing happens in client.
If need more test/info please tell me 

Tnks

**Comment by Zaexides** [comment]
Okay, yeah, I can't seem to reproduce it myself either right now. I'd say it's either an issue with the Steam Generator or with Ender IO's fluid conduit. Ender IO does seem to have compatibility issues with other mods after all, according to their CurseForge page, but I'll keep an eye out on the issue.
In the meanwhile I'd advice making sure that Ender IO is up-to-date.

**Comment by navaroneee** [comment]
Yes yes, I keep all the updated mods constantly, I will carry out more tests, in case I have to contact you again.

sorry my bad english
