### ISSUE TITLE
LumberJack not collecting chopped things

### ISSUE THREAD

**Issue by jellonek** [Zaexides/SteamWorld#17]
As in subject - lumberjack drops apples/logs/saplings everywhere around instead collecting them in internal inventory (which is constantly empty).

Appearing in https://minecraft.curseforge.com/projects/steam-engineering-2 with 0.3.1 version of SteamWorld under 1.12.2/14.23.4.2705 minecraft/forge.

**Comment by Zaexides** [comment]
Thank you for bringing this oversight to my attention, it'll be fixed in the next update!
