### ISSUE TITLE
Broken input slots

### ISSUE THREAD

**Issue by Yoosk** [Zaexides/SteamWorld#2]
* **What's the type of issue?**
  * *Bug report/Content or Mechanic change suggestion/Misc.*

### Bug Report
  * **What's the mod version?**
    * *SteamWorld 1.12.2-0.2.3.2*

  * **What's the forge version?**
    * *14.23.0.2531*

  * **What were you doing when the bug occurred?**
    * *was seting up automation for grinder, furnace using xnet*

  * **What happened that should not have happened?**
    * *ore's go into both input and output slot, see image*
https://i.imgur.com/jIXTxyG.png

**Comment by Zaexides** [comment]
Alright, this has been fixed (and tested) and will be deployed in the next update.
