### ISSUE TITLE
SteamWorld+JEI (errors)

### ISSUE THREAD

**Issue by kellixon** [Zaexides/SteamWorld#22]
MC 1.12.2. Forge 14.23.5.2768. SteamWorld 0.4.0.1.
Serious errors (lines 15235, 15293)?
Full log (60772 lines) - https://gist.github.com/kellixon/996af14754efd941449c47ea4c8fc56d

**Comment by Zaexides** [comment]
Thanks for reporting this, this should be fixed alongside the previous fix
