### ISSUE TITLE
Seeds duplication

### ISSUE THREAD

**Issue by Yoosk** [Zaexides/SteamWorld#3]
* **What's the type of issue?**
  * *Bug report/Content or Mechanic change suggestion/Misc.*

### Bug Report
  * **What's the mod version?**
    * *SteamWorld 1.12.2-0.2.3.2*

  * **What's the forge version?**
    * *14.23.0.2531*

  * **What were you doing when the bug occurred?**
    * *Was setting up a farm of Mystical Agriculture seeds using farmer*

  * **What happened that should not have happened?**
    * *Seeds are getting duplicated against configuration from Mystical Agriculture, which says 0% chance for secondary seed.*

**Comment by Zaexides** [comment]
I'm going to label this as a suggestion rather than a bug since the upgraded farmer producing extra seeds is intended behaviour. I'll consider this for (future) balancing, however.

**Comment by ouroborus** [comment]
@Zaexides I'd like to point out that Mystical Agriculture is a special snowflake of a mod. Generally, other mods handle MA's seeds by never producing them through harvesting and only producing the one, original seed through breaking.

**Comment by Zaexides** [comment]
@ouroborus Thanks for the info! I'll probably add in a config option to blacklist certain crop results, might also reduce or remove the extra seed production as the extra production of any seed at all seems a bit excessive.

**Comment by Zaexides** [comment]
Alright, I've added a couple of config options for the farmer. One option to disable the upgrades affecting the seed drops (this may cause seeds to not drop at all) and a blacklist. Planning to release an updated version this weekend.
