### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by yujukitten** [Zaexides/SteamWorld#6]
* **What's the type of issue?**
Content or Mechanic change suggestion

  * **What's the mod version?**

1.12.2-0.2.4.0 
  * **What's the forge version?**
    * *Forge (minecraft version) - (forge version)*
12.2 2555

  * **What happened that should not have happened?**
 After a few hours of gameplay with the steam machines and fluid connectors up and running on the server the tickrate of them becomes really high 50+ (especially the fluid connector/ conduit ). It really impedes performance 
  
  * **Please post your crashlog and forge logs here.**
    I could get some pictures of the tickrate monitor ? if they are useful ? I use the LagGoggles Mod to find these issues.
    

  * **Why is this change a change for the better?**
   If it was able to maintain low tickrate it would improve overall performance. I have not tested this in Single player but I know on the server it has causes some rubber-banding as well as general lag spikes.

**Comment by Zaexides** [comment]
Thank you for the information, it'd help greatly if you could provide additional information, but I can understand that you may be limited in getting that additional information. I'll be looking at this as soon as my schedule allows me, but in the meantime you _should_ be able to adjust the update time for the Fluid Controller in the config file without too many complications.

**Comment by Zaexides** [comment]
Alright, I pretty much rewrote the Fluid Controller, should be faster now starting from 1.12.2-0.3, expect a release hopefully soon™
